'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={data:null,archive:null,password:'',view:'home',mode:'week',anchor:new Date(),actions:[],deviceId:localStorage.getItem('sc_device')||crypto.randomUUID()};
localStorage.setItem('sc_device',state.deviceId);
const TERMINAL=new Set(['DEFINITA','DEFINITO','ARCHIVIATA','ARCHIVIATO','CHIUSA','CHIUSO']);
function clean(v){return (v??'').toString().trim()} function up(v){return clean(v).toUpperCase().replaceAll('_',' ')}
function isoDate(d){const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`}
function parseDate(s){const p=clean(s).slice(0,10).split('-').map(Number);return p.length===3?new Date(p[0],p[1]-1,p[2]):null}
function fmt(s){const d=parseDate(s);return d?new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d):clean(s)}
function escapeHtml(s){return clean(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function b64uToBytes(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
function bytesToB64u(bytes){let raw='';for(const b of bytes)raw+=String.fromCharCode(b);return btoa(raw).replace(/\+/g,'-').replace(/\//g,'_')}
async function keyFromPassword(password,salt,iterations){const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt,iterations},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function decryptArchive(env,password){if(env.format!=='SCM1')throw new Error('Formato .scmobile non riconosciuto');const key=await keyFromPassword(password,b64uToBytes(env.salt),Number(env.iterations||300000));const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64uToBytes(env.nonce),additionalData:new TextEncoder().encode('STUDIO-COSTA-COMPANION-SCM1')},key,b64uToBytes(env.ciphertext));return JSON.parse(new TextDecoder().decode(plain))}
async function makeResponse(){if(!state.actions.length)throw new Error('Non ci sono modifiche da esportare.');const payload={format:'SCMR1',sourceGeneratedAt:state.archive?.exportedAt||'',deviceId:state.deviceId,createdAt:new Date().toISOString(),actions:state.actions};const salt=crypto.getRandomValues(new Uint8Array(16)),nonce=crypto.getRandomValues(new Uint8Array(12)),iterations=300000,key=await keyFromPassword(state.password,salt,iterations);const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv:nonce,additionalData:new TextEncoder().encode('STUDIO-COSTA-COMPANION-SCMR1')},key,new TextEncoder().encode(JSON.stringify(payload)));return {format:'SCMR1',iterations,salt:bytesToB64u(salt),nonce:bytesToB64u(nonce),ciphertext:bytesToB64u(new Uint8Array(cipher))}}
function operationalPractice(p){return p&&!TERMINAL.has(up(p.stato||p.status))&&!up(p.tipologia_difesa).includes('CESSATA')&&!up(p.stato_difesa).includes('CESSAT')}
function events(){return (state.data?.events||[]).filter(e=>{if(e.practice_id){const p=(state.data.practices||[]).find(x=>Number(x.id)===Number(e.practice_id));if(p&&!operationalPractice(p))return false}return !['ANNULLATA','CANCELLATA','COMPLETATA','COMPLETATO','DEPOSITATA'].includes(up(e.status))})}
function eventKind(e){const c=up(e.category),s=up(e.source_type);if(c.includes('UDIENZA')||s.includes('HEARING'))return 'hearing';if(c==='CRESET'||s.includes('CRESET'))return 'creset';if(c.includes('SCADEN')||e.legal_deadline)return 'deadline';if(c.includes('CHECKLIST'))return 'checklist';return 'activity'}
const CHECKLIST_CARD_CLASS='agenda-category-card kind-CHECKLIST';
const AGENDA_GROUPS=[{kinds:["UDIENZA"],title:"Udienze",css:"UDIENZA"},{kinds:["APPUNTAMENTO"],title:"Appuntamenti",css:"APPUNTAMENTO"},{kinds:["SCADENZA"],title:"Scadenze",css:"SCADENZA"},{kinds:["CRESET"],title:"Creset",css:"CRESET"},{kinds:["CHECKLIST"],title:"Checklist",css:"CHECKLIST"},{kinds:["ATTIVITA"],title:"Attività",css:"ATTIVITA"}];
function queueMobileAction(...args){return addAction(...args)} function exportMobileActions(){return exportChanges()} function openLocalTask(uid){return openEvent(uid)}
function bounds(mode,anchor){const d=new Date(anchor);d.setHours(0,0,0,0);if(mode==='today')return [d,d];if(mode==='week'){const delta=(d.getDay()+6)%7,a=new Date(d);a.setDate(d.getDate()-delta);const b=new Date(a);b.setDate(a.getDate()+6);return[a,b]}const a=new Date(d.getFullYear(),d.getMonth(),1),b=new Date(d.getFullYear(),d.getMonth()+1,0);return[a,b]}
function between(iso,a,b){const d=parseDate(iso);return d&&d>=a&&d<=b}
function periodLabel(a,b,mode){if(mode==='today')return fmt(isoDate(a));if(mode==='week')return `${fmt(isoDate(a))} – ${fmt(isoDate(b))}`;return new Intl.DateTimeFormat('it-IT',{month:'long',year:'numeric'}).format(a)}
function stepPeriod(dir){const d=new Date(state.anchor);d.setDate(d.getDate()+dir*(state.mode==='today'?1:state.mode==='week'?7:0));if(state.mode==='month')d.setMonth(d.getMonth()+dir);state.anchor=d;render()}
function addAction(type,targetId,payload={},extra={}){state.actions.push({actionId:crypto.randomUUID(),actionType:type,targetId,actionAt:new Date().toISOString(),sourceUpdatedAt:extra.sourceUpdatedAt||'',payload,...extra});saveLocal();renderTopNotice()}
function renderTopNotice(){let n=$('#pendingNotice');if(!state.actions.length){if(n)n.remove();return}if(!n){n=document.createElement('div');n.id='pendingNotice';n.className='notice';$('#app').prepend(n)}n.innerHTML=`${state.actions.length} modifica/e da riportare sul PC. <button class="secondary" id="exportChanges">Esporta .scmr</button>`;$('#exportChanges').onclick=exportChanges}
async function importFile(file){const text=await file.text();const env=JSON.parse(text);const password=prompt('Password dell’aggiornamento .scmobile:');if(!password)return;const payload=await decryptArchive(env,password);state.archive=payload;state.data=payload.data||{};state.password=password;state.actions=[];await saveLocal();state.anchor=new Date();state.view='home';render()}
function openImport(){const input=$('#fileInput');if(!input)return;try{if(typeof input.showPicker==='function'){input.showPicker();return}}catch(_){}input.click()}
function showModal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function eventHtml(e){const k=eventKind(e),taskAttr=up(e.source_type)==='TASK'?` data-task-complete="${escapeHtml(e.source_id||'')}"`:'',hearAttr=k==='hearing'?` data-hearing-manage="${escapeHtml(e.source_id||'')}"`:'';return `<div class="event ${k}" data-event="${escapeHtml(e.uid||'')}"${taskAttr}${hearAttr}><div class="when">${fmt(e.event_date)} ${escapeHtml(e.start_time||'')}</div><div class="title">${escapeHtml(e.title||e.category||'Impegno')}</div><div class="meta">${escapeHtml([e.practice_name,e.practice_code,e.location].filter(Boolean).join(' · '))}</div></div>`}
function wireEvents(){$$('[data-event]').forEach(el=>el.onclick=()=>openEvent(el.dataset.event))}
function openEvent(uid){const e=events().find(x=>clean(x.uid)===clean(uid))||(state.data.events||[]).find(x=>clean(x.uid)===clean(uid));if(!e)return;let actions='';if(up(e.source_type)==='TASK'){const done=['COMPLETATA','DEPOSITATA'].includes(up(e.status));actions=`<button class="primary" id="taskToggle">${done?'Riapri':'Segna completata'}</button>`}showModal(e.title||'Dettaglio',`<div class="muted-box"><b>${fmt(e.event_date)} ${escapeHtml(e.start_time||'')}</b><br>${escapeHtml(e.practice_name||'')}<br>${escapeHtml(e.location||'')}</div><p>${escapeHtml(e.notes||'')}</p><div class="actions">${actions}</div>`);if($('#taskToggle'))$('#taskToggle').onclick=()=>{const done=['COMPLETATA','DEPOSITATA'].includes(up(e.status));addAction('task_status',e.source_id,{newStatus:done?'DA FARE':'COMPLETATA'},{taskId:e.source_id,sourceUpdatedAt:e.updated_at||''});closeModal()}}
function periodToolbar(){return `<div class="toolbar"><div class="seg">${[['today','Oggi'],['week','Settimana'],['month','Mese']].map(([v,l])=>`<button data-mode="${v}" class="${state.mode===v?'active':''}">${l}</button>`).join('')}</div><div class="navdate"><button id="prevPeriod">‹</button><button id="goToday">Oggi</button><button id="nextPeriod">›</button></div></div>`}
function wirePeriod(){$$('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;render()});$('#prevPeriod').onclick=()=>stepPeriod(-1);$('#nextPeriod').onclick=()=>stepPeriod(1);$('#goToday').onclick=()=>{state.anchor=new Date();render()}}
function renderHome(){const [a,b]=bounds(state.mode,state.anchor),list=events().filter(e=>between(e.event_date,a,b)).sort((x,y)=>(x.event_date+x.start_time).localeCompare(y.event_date+y.start_time));const counts={hearing:0,deadline:0,creset:0,activity:0};list.forEach(e=>counts[eventKind(e)]!==undefined&&counts[eventKind(e)]++);let html=`<h1 class="section-title">La mia agenda</h1>${periodToolbar()}<div class="period">${periodLabel(a,b,state.mode)}</div><div class="metrics"><div class="metric"><b>${counts.hearing}</b><span>Udienze</span></div><div class="metric"><b>${counts.deadline}</b><span>Scadenze</span></div><div class="metric"><b>${counts.creset}</b><span>Creset</span></div><div class="metric"><b>${counts.activity}</b><span>Attività</span></div></div>`;if(state.mode==='week'){html+=weekStrip(a,list);const agendaSelectedDay=isoDate(state.anchor);html+=weekOverview(list,a,agendaSelectedDay,"data-agenda-week-day").includes('weekstrip')?'':'';const selected=list.filter(e=>e.event_date===agendaSelectedDay);html+=agendaCategoryCards(selected.length?selected:list)}else if(state.mode==='month')html+=monthGrid(a,list);else html+=groupedEvents(list);$('#app').innerHTML=html;wirePeriod();wireEvents();wireWeek();renderTopNotice()}
function groupedEvents(list){if(!list.length)return '<div class="card subtle">Nessun impegno nel periodo.</div>';const groups={};for(const e of list)(groups[e.event_date]??=[]).push(e);return Object.keys(groups).sort().map(d=>`<div class="day-group"><div class="day-label">${fmt(d)}</div>${groups[d].map(eventHtml).join('')}</div>`).join('')}

function agendaCategoryCards(list){const groupFor=e=>eventKind(e)==='hearing'?'UDIENZA':eventKind(e)==='deadline'?'SCADENZA':eventKind(e)==='creset'?'CRESET':eventKind(e)==='checklist'?'CHECKLIST':up(e.category).includes('APPUNT')?'APPUNTAMENTO':'ATTIVITA';return AGENDA_GROUPS.map(group=>{const vals=list.filter(e=>group.kinds.includes(groupFor(e)));if(!vals.length)return '';return `<section class="agenda-category-card kind-${group.css}"><h3>${group.title}</h3>${vals.map(eventHtml).join('')}</section>`}).join('')}
function weekOverview(all,start,agendaSelectedDay,attr='data-agenda-week-day'){let out='<div class="weekstrip">';for(let i=0;i<7;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=isoDate(d),n=all.filter(e=>e.event_date===iso).length;out+=`<button class="daybtn ${iso===agendaSelectedDay?'active':''}" ${attr}="${iso}" data-day="${iso}"><b>${['LUN','MAR','MER','GIO','VEN','SAB','DOM'][i]}</b><span>${d.getDate()}</span><small>${n||'–'}</small></button>`}return out+'</div>'}
function weekStrip(a,list){const agendaSelectedDay=isoDate(state.anchor);return weekOverview(list,a,agendaSelectedDay,"data-agenda-week-day")}
function wireWeek(){$$('[data-day]').forEach(b=>b.onclick=()=>{state.anchor=parseDate(b.dataset.day);state.mode='today';render()})}
function monthGrid(a,list){const first=new Date(a),gridStart=new Date(first);gridStart.setDate(first.getDate()-((first.getDay()+6)%7));let out='<div class="monthgrid">';for(let i=0;i<42;i++){const d=new Date(gridStart);d.setDate(gridStart.getDate()+i);const iso=isoDate(d),vals=list.filter(e=>e.event_date===iso);out+=`<div class="monthcell ${d.getMonth()===first.getMonth()?'':'other'}" data-day="${iso}"><b>${d.getDate()}</b><div class="dots">${vals.slice(0,4).map(e=>eventKind(e)==='hearing'?'● U':eventKind(e)==='deadline'?'● S':eventKind(e)==='creset'?'● C':'● A').join('<br>')}</div></div>`}return out+'</div>'}
function renderAgenda(){const all=events(),[start]=bounds('week',state.anchor),agendaSelectedDay=isoDate(state.anchor);void weekOverview(all,start,agendaSelectedDay,"data-agenda-week-day");renderHome()}
function renderPractices(){const ps=state.data?.practices||[];$('#app').innerHTML=`<h1 class="section-title">Pratiche</h1><input id="practiceSearch" class="search" placeholder="Cerca assistito, RG, RGNR…"><div id="practiceList">${practiceCards(ps)}</div>`;$('#practiceSearch').oninput=e=>$('#practiceList').innerHTML=practiceCards(ps.filter(p=>JSON.stringify(p).toLowerCase().includes(e.target.value.toLowerCase())));wirePractices();renderTopNotice()}
function practiceCards(ps){return ps.map(p=>`<div class="card practice" data-practice="${p.id}"><h3>${escapeHtml(p.assistito||'Pratica')}</h3><span class="badge">${escapeHtml(p.area||'')}</span><span class="badge">${escapeHtml(p.numero_principale||p.rg||'')}</span><div class="subtle">${escapeHtml(p.oggetto||p.materia||'')}</div></div>`).join('')||'<div class="card subtle">Nessuna pratica disponibile.</div>'}
function wirePractices(){$$('[data-practice]').forEach(x=>x.onclick=()=>openPractice(Number(x.dataset.practice)))}
function openPractice(id){const p=(state.data.practices||[]).find(x=>Number(x.id)===id);if(!p)return;const cls=(state.data.checklists||[]).filter(c=>Number(c.practice_id)===id);let ch=cls.map(c=>{const items=(state.data.checklistItems||[]).filter(i=>clean(i.checklist_id)===clean(c.checklist_id));return `<div class="card"><b>${escapeHtml(c.title)}</b><div class="subtle">${fmt(c.date)}</div>${items.map(i=>`<label class="checkrow"><input type="checkbox" data-checkitem="${escapeHtml(i.checklist_item_id)}" ${up(i.status)==='COMPLETATA'?'checked':''}><span>${escapeHtml(i.title)} <small>${fmt(i.due_date)} ${escapeHtml(i.due_time||'')}</small></span></label>`).join('')}</div>`}).join('');showModal(p.assistito||'Pratica',`<div class="muted-box"><b>${escapeHtml(p.area||'')}</b> · ${escapeHtml(p.numero_principale||'')}<br>${escapeHtml(p.autorita||'')}<br>${escapeHtml(p.fase||'')}</div><h3>Checklist</h3>${ch||'<p class="subtle">Nessuna checklist collegata.</p>'}<div class="actions"><button class="primary" id="newChecklistPractice">＋ Nuova checklist</button></div>`);$$('[data-checkitem]').forEach(cb=>cb.onchange=()=>{const item=(state.data.checklistItems||[]).find(i=>clean(i.checklist_item_id)===clean(cb.dataset.checkitem));addAction(cb.checked?'complete_checklist_item':'reopen_checklist_item',cb.dataset.checkitem,{newStatus:cb.checked?'COMPLETATA':'DA_FARE'},{checklistItemId:cb.dataset.checkitem,sourceUpdatedAt:item?.updated_at||''})});$('#newChecklistPractice').onclick=()=>openChecklistForm(id)}
function openChecklistForm(practiceId=''){const opts=(state.data.practices||[]).map(p=>`<option value="${p.id}" ${Number(p.id)===Number(practiceId)?'selected':''}>${escapeHtml(p.assistito||p.numero_principale)}</option>`).join('');showModal('Nuova checklist',`<div class="field"><label>Titolo</label><input id="clTitle" value="Checklist"></div><div class="field"><label>Data</label><input id="clDate" type="date" value="${isoDate(new Date())}"></div><div class="field"><label>Pratica (facoltativa)</label><select id="clPractice"><option value="">Nessuna pratica</option>${opts}</select></div><div class="field"><label>Priorità</label><select id="clPriority"><option>MEDIA</option><option>ALTA</option><option>URGENTE</option><option>BASSA</option></select></div><div class="field"><label>Elenco — una voce per riga</label><textarea id="clItems" placeholder="Telefonare al cliente\nControllare documenti\nPreparare deposito"></textarea></div><div class="actions"><button class="primary" id="saveChecklist">Crea checklist</button></div>`);$('#saveChecklist').onclick=()=>{const items=$('#clItems').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!$('#clTitle').value.trim()||!$('#clDate').value||!items.length){alert('Inserire titolo, data e almeno una voce.');return}const uid=crypto.randomUUID();addAction('upsert_checklist',uid,{title:$('#clTitle').value.trim(),date:$('#clDate').value,practice_id:Number($('#clPractice').value)||null,priority:$('#clPriority').value,items:items.map(t=>({title:t,due_date:$('#clDate').value,priority:$('#clPriority').value}))},{mobile_uid:uid});closeModal()}}
function renderCreset(){const rows=state.data?.creset||[];$('#app').innerHTML=`<h1 class="section-title">Creset</h1><div class="subtle" style="margin-bottom:10px">Posizioni operative e relativi adempimenti.</div>${rows.map(r=>`<div class="card creset-row"><b>${escapeHtml(r.taxpayer||'Posizione')}</b><div class="subtle">${escapeHtml(r.municipality||'')} · RG ${escapeHtml(r.rg_number||'')}</div><p>Verifica: <b>${fmt(r.verification_due_date)||'—'}</b><br>Preparazione: <b>${fmt(r.preparation_due_date)||'—'}</b><br>Deposito: <b>${fmt(r.filing_due_date)||'—'}</b><br>Udienza: <b>${fmt(r.hearing_date)||'—'} ${escapeHtml(r.hearing_time||'')}</b></p><div class="actions"><button class="secondary" data-creset-work="${r.id}">Segna lavorata</button><button class="primary" data-creset-const="${r.id}">Costituita</button></div></div>`).join('')||'<div class="card subtle">Nessuna posizione Creset operativa.</div>'}`;$$('[data-creset-work]').forEach(b=>b.onclick=()=>{const r=rows.find(x=>Number(x.id)===Number(b.dataset.cresetWork));addAction('creset_set_status',r.id,{newStatus:'LAVORATA'},{positionId:r.id,sourceUpdatedAt:r.updated_at||''})});$$('[data-creset-const]').forEach(b=>b.onclick=()=>{const r=rows.find(x=>Number(x.id)===Number(b.dataset.cresetConst));addAction('creset_set_status',r.id,{newStatus:'COSTITUITA'},{positionId:r.id,sourceUpdatedAt:r.updated_at||''})});renderTopNotice()}
function openQuickAdd(){showModal('Nuovo elemento',`<div class="actions"><button class="primary" id="qaChecklist">Checklist</button><button class="secondary" id="qaTask">Attività</button><button class="secondary" id="qaAppointment">Appuntamento</button><button class="secondary" id="qaHearing">Udienza</button></div>`);$('#qaChecklist').onclick=()=>openChecklistForm();$('#qaTask').onclick=()=>openItemForm('upsert_task','Attività');$('#qaAppointment').onclick=()=>openItemForm('upsert_appointment','Appuntamento');$('#qaHearing').onclick=()=>openItemForm('upsert_hearing','Udienza')}
function openItemForm(type,label){const opts=(state.data.practices||[]).map(p=>`<option value="${p.id}">${escapeHtml(p.assistito||p.numero_principale)}</option>`).join('');const needPractice=type==='upsert_hearing';showModal('Nuova '+label,`<div class="field"><label>Titolo</label><input id="itTitle" value="${label}"></div><div class="field"><label>Data</label><input id="itDate" type="date" value="${isoDate(new Date())}"></div><div class="field"><label>Ora</label><input id="itTime" type="time"></div><div class="field"><label>Pratica ${needPractice?'(obbligatoria)':'(facoltativa)'}</label><select id="itPractice"><option value="">Nessuna</option>${opts}</select></div><div class="field"><label>Note / luogo</label><textarea id="itNotes"></textarea></div><div class="actions"><button class="primary" id="itSave">Salva nel Companion</button></div>`);$('#itSave').onclick=()=>{if(!$('#itTitle').value.trim()||!$('#itDate').value||(needPractice&&!$('#itPractice').value)){alert('Completare i campi obbligatori.');return}const uid=crypto.randomUUID(),payload={title:$('#itTitle').value.trim(),date:$('#itDate').value,start_time:$('#itTime').value,practice_id:Number($('#itPractice').value)||null,notes:$('#itNotes').value,category:label.toUpperCase(),location:$('#itNotes').value};addAction(type,uid,payload,{mobile_uid:uid});closeModal()}}
async function exportChanges(){try{if(!state.password){const p=prompt('Password usata per il pacchetto .scmobile:');if(!p)return;state.password=p}const env=await makeResponse();const blob=new Blob([JSON.stringify(env,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`StudioCosta_Risposte_${new Date().toISOString().slice(0,16).replace(/[:T]/g,'-')}.scmr`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){alert(e.message)}}
async function saveLocal(){try{localStorage.setItem('sc_snapshot',JSON.stringify({archive:state.archive,data:state.data,actions:state.actions}))}catch(_){}}
function loadLocal(){try{const o=JSON.parse(localStorage.getItem('sc_snapshot')||'null');if(o?.data){state.archive=o.archive;state.data=o.data;state.actions=Array.isArray(o.actions)?o.actions:[];state.password=''}}catch(_){}}
function render(){if(!state.data){$('#app').innerHTML='<section class="empty"><h1>Studio Costa Companion</h1><p>Importa l’aggiornamento cifrato creato dal gestionale desktop.</p><label for="fileInput" id="firstImport" class="primary file-trigger" role="button" tabindex="0">Importa .scmobile</label></section>';return}$$('.bottomnav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));if(state.view==='home')renderHome();else if(state.view==='agenda')renderAgenda();else if(state.view==='practices')renderPractices();else renderCreset()}
$('#fileInput').onchange=e=>{if(e.target.files[0])importFile(e.target.files[0]).catch(err=>alert('Importazione non riuscita: '+err.message));e.target.value=''};$$('.file-trigger').forEach(el=>el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openImport()}});$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};$('#fab').onclick=openQuickAdd;$$('.bottomnav button').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});loadLocal();render();if('serviceWorker' in navigator && location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').then(r=>r.update()).catch(()=>{});
